on:
  push:
    paths:
    - boards/**
    - config/**
    - drivers/**
    - dts/**
    - zephyr/**
    - build.yaml
    - CMakeLists.txt
    - Kconfig
  pull_request:
    paths:
    - boards/**
    - config/**
    - drivers/**
    - dts/**
    - zephyr/**
    - build.yaml
    - CMakeLists.txt
    - Kconfig
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
